services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/frontend
      - ./backend:/var/www/backend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - php

  php:
    build: ./docker/php
    container_name: php
    ports:
      - "9000"
    volumes:
      - ./frontend:/var/www/frontend
      - ./backend:/var/www/backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=docker-php"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=host.docker.internal
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=
      - PMA_AUTOLOGIN=1
    depends_on:
      - php

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: ../docker/react/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start -- --host"
